server:
  port: 9000

spring:
  application:
    name: demo

  datasource:
    platform: mysql
    url: jdbc:mysql://inpro-db.cxc4qfeihpqh.ap-northeast-2.rds.amazonaws.com/test?autoReconnect=true
    username:
    password:
    driver-class-name: com.mysql.cj.jdbc.Driver